const content = {
  en: {
    institutionName: "Ishtar Institution",
    title: "Technical Support",
    subtitle: "Enter your issue and we will help you.",
    emailLabel: "Email Address",
    emailPlaceholder: "Enter your email",
    subjectLabel: "Subject",
    subjectPlaceholder: "Subject of the issue",
    messageLabel: "Problem Description",
    messagePlaceholder: "Describe your problem...",
    submit: "Submit",
    success: "Your message has been sent successfully! ✅",
    successSub: "We will get back to you as soon as possible.",
    error: "Failed to send. Please check your connection and try again.",
    errRequired: "This field is required",
    errEmail: "Invalid email format",
    errShort: "Message is too short",
    sending: "Sending...",
  },
  ar: {
    institutionName: "معهد عشتار",
    title: "الدعم التقني",
    subtitle: "أدخل مشكلتك وسنساعدك.",
    emailLabel: "البريد الإلكتروني",
    emailPlaceholder: "أدخل بريدك الإلكتروني",
    subjectLabel: "الموضوع",
    subjectPlaceholder: "موضوع المشكلة",
    messageLabel: "وصف المشكلة",
    messagePlaceholder: "اشرح مشكلتك...",
    submit: "إرسال",
    success: "تم إرسال رسالتك بنجاح! ✅",
    successSub: "سنتواصل معك في أقرب وقت ممكن.",
    error: "فشل الإرسال. تحقق من اتصالك وحاول مجدداً.",
    errRequired: "هذا الحقل مطلوب",
    errEmail: "صيغة الإيميل غير صحيحة",
    errShort: "الرسالة قصيرة جداً",
    sending: "جاري الإرسال...",
  },
};

export default content;